### ISSUE TITLE
第三题PTA判定

### ISSUE THREAD

**Issue by Joycer-hack** [wood3/ask33#1]
#include<bits/stdc++.h>
using namespace std;
int n,k,m;
struct Stu{
	int sum;
	int name;
	int solved;
	bool show;
	int rank;
	int score[6];
};
bool f(Stu x,Stu y){
	if(x.sum>y.sum) return x.sum>y.sum;
	else y.sum>x.sum ;
	if(x.solved >y.solved )return x.solved >y.solved ;
	else x.solved <y.solved ;
	return x.name <y.name;
}
Stu a[10000+10];
int b[6];
int x,y,z;
int main(){
cin>>n>>k>>m;
for(int i=1;i<=k;i++){
	scanf("%d",&b[i]);
}
memset(a,-1,sizeof(a));
for(int i=1;i<=n;i++){
	for(int j=1;j<=k;j++) a[i].score[j]=-1;
	a[i].solved =0;
	a[i].show =false;
	a[i].sum =0;
}

for(int i=0;i<m;i++){
	cin>>x>>y>>z;
	if(z!=-1) a[x].show =true;
	if(z>a[i].score[y]) a[i].score[y]=z;
	if(z==b[y]) a[i].solved ++;
}
for(int i=1;i<=n;i++){
	for(int j=1;j<=k;j++) 
		if(a[i].score[j]!=-1) a[i].sum+=a[i].score[j];
}
sort(a+1,a+n+1,f);
for(int i=1;i<=n;i++){
	a[i].rank=i;
	if(i!=1&&a[i].sum==a[i-1].sum) a[i].rank=a[i-1].rank;
}
for(int i=1;i<=n;i++){
	if(a[i].show==false) continue;
	printf("%d",a[i].rank);
	printf(" %05d",a[i].name );
	printf(" %d",a[i].sum);
	for(int j=1;j<=k;j++){
		if(a[i].score[j]!=-1) printf(" %d",a[i].score[j]);
		else printf(" -");
	}
	printf("\n");
}
return 0;
}

**Comment by Joycer-hack** [comment]
多种错误

**Comment by Joycer-hack** [comment]
样例可以出来

**Comment by wood3** [comment]
emmmm以后代码用代码的格式发一下，
```
先写：```cpp
贴代码代码
然后下一行写：```
```
这道题网站你们权限题，我没法去评测
